# Form implementation generated from reading ui file 'MyForm.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_myForm(object):
    def setupUi(self, myForm):
        myForm.setObjectName("myForm")
        myForm.resize(300, 70)
        self.horizontalLayout = QtWidgets.QHBoxLayout(myForm)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=myForm)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.btnQuit = QtWidgets.QPushButton(parent=myForm)
        self.btnQuit.setObjectName("btnQuit")
        self.verticalLayout.addWidget(self.btnQuit)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(myForm)
        QtCore.QMetaObject.connectSlotsByName(myForm)

    def retranslateUi(self, myForm):
        _translate = QtCore.QCoreApplication.translate
        myForm.setWindowTitle(_translate("myForm", "Form"))
        self.label.setText(_translate("myForm", "TextLabel"))
        self.btnQuit.setText(_translate("myForm", "Выход"))
